%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/melodic/.*$
%global __requires_exclude_from ^/opt/ros/melodic/.*$

Name:           ros-melodic-xacro
Version:        1.13.5
Release:        1%{?dist}
Summary:        ROS xacro package

License:        BSD
URL:            http://ros.org/wiki/xacro
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-melodic-roslaunch
BuildRequires:  ros-melodic-catkin >= 0.5.68
BuildRequires:  ros-melodic-roslint
BuildRequires:  ros-melodic-rostest

%description
Xacro (XML Macros) Xacro is an XML macro language. With xacro, you can construct
shorter and more readable XML files by using macros that expand to larger XML
expressions.

%prep
%autosetup

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_LIBDIR="lib" \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/melodic

%changelog
* Sun Dec 08 2019 Robert Haschke <rhaschke@techfak.uni-bielefeld.de> - 1.13.5-1
- Autogenerated by Bloom

* Thu Sep 26 2019 Robert Haschke <rhaschke@techfak.uni-bielefeld.de> - 1.13.4-1
- Autogenerated by Bloom

* Sun Oct 14 2018 Robert Haschke <rhaschke@techfak.uni-bielefeld.de> - 1.13.3-0
- Autogenerated by Bloom

* Mon May 14 2018 Robert Haschke <rhaschke@techfak.uni-bielefeld.de> - 1.13.2-0
- Autogenerated by Bloom

* Thu May 03 2018 Robert Haschke <rhaschke@techfak.uni-bielefeld.de> - 1.13.1-0
- Autogenerated by Bloom

* Sat Mar 31 2018 Robert Haschke <rhaschke@techfak.uni-bielefeld.de> - 1.13.0-0
- Autogenerated by Bloom

